/**
 * 
 */
package sv.com.epsilon.staticvalues;

/**
 * @author martinezc
 *
 */
public class Customers {

	/**
	 * 
	 */
	public Customers() {
		
	}
	
	public final static String VALUES="GRUPO IMPRESIONARTE S.A. DE C.V.-"
			+ "VICTOR MANUEL VASQUEZ PEÑA-"
			+ "DEPOSITO 11 PRESUPUESTO FPT AÑO 2023-"
			+ "JULIO ALEXANDER AGUILLON HERNANDEZ-"
			+ "ARISTA DE EL SALVADOR-"
			+ "TALLER DIDEA, S.A. DE C.V.-"
			+ "ITECS S.A. DE C.V.-"
			+ "ARISTIDES ALEXANDER HERNANDEZ VALDEZ-"
			+ "TOMAS ISRAEL CRUZ GUILLEN-"
			+ "LA CONSTANCIA LTDA DE C.V.-"
			+ "JOHNNY OMAR RIVAS AYALA-"
			+ "PROVEEDORA ELECTRICA EL SALVADOR S.A. DE C.V.-"
			+ "EDUARDO AVILES RAMIREZ-"
			+ "ALMACENES VIDRI, S.A. DE C.V.-"
			+ "MAURICIO AMILCAR DOMINGUEZ ALVARENGA-"
			+ "FREUND, S.A. DE C.V.-"
			+ "JOSE OMAR ALVARENGA GUEVARA-"
			+ "AFP CONFIA, S.A.-"
			+ "AFP CRECER, S.A.-"
			+ "INSTITUTO SALVADOREÑO DE SEGURO SOCIAL-"
			+ "JUAN CARLOS URBINA HERNANDEZ-"
			+ "MIGUEL ANTONIO GONZALEZ GONZALEZ-"
			+ "BRAULIO MARTINEZ ELIAS-"
			+ "COMISION POR PLANILLA PRIMERA QUINCENA DE NOVIEMBRE 2023-"
			+ "PLANILLA SUELDO 1 Q NOVIEMBRE DE 2023-"
			+ "ANGEL SAMUEL LOPEZ JUAREZ-"
			+ "MILAGRO CAROLINA CASCO GUZMAN-"
			+ "MINISTERIO DE HACIENDA-"
			+ "FERRETERIA EPA S.A. DE C.V.-"
			+ "TOROGOZ, S.A. DE C.V. -"
			+ "CAESS. S.A DE C.V.-"
			+ "SOLARTECH CENTROAMERICA, S.A. DE C.V.-"
			+ "ACOMIC-"
			+ "ARANDA, S.A. DE C.V. -"
			+ "CESAR WILFREDO VASQUEZ VASQUEZ -"
			+ "GRUPO IMPRESIONARTE S.A. DE C.V.-"
			+ "FUNDACION PABLO TESAK-"
			+ "DIEGO GERARDO CHOTO LOPEZ-"
			+ "INVERSIONES RAMIREZ QUINTANILLA S.A. DE C.V.-"
			+ "CTE TELECOM PERSONAL , S.A. DE C.V.-"
			+ "COMPAÑÍA DE TELECOMUNICACIONES DE EL SALVADOR, S.A. DE C.V.-"
			+ "RICARDO ERNESTO RIVAS ROMERO-"
			+ "CALTEC, S.A. DE C.V.-"
			+ "COMISION POR PLANILLA SEGUNDA QUINCENA DE NOVIEMBRE 2023-"
			+ "PLANILLA SUELDO 2 Q NOVIEMBRE DE 2023-"
			+ "COMERCIAL DE PLASTICOS S.A. DE C.V.-"
			+ "JAVIER EDUARDO MARTINEZ RODAS-"
			+ "FANNY MELISSA HERNANDEZ DE MELGAR-"
			+ "DEPOSITO 12 PRESUPUESTO FPT AÑO 2023-"
			+ "MTECH-"
			+ "VIDUC S.A. DE C.V.-"
			+ "DINA MARGARITA MENDOZA DE CHRISTOPHE-"
			+ "WILFREDO ANTONIO ARGUETA RAMOS-"
			+ "SEGUROS SURA, S.A.-"
			+ "LORENA GUADALUPE CRUZ MARROQUIN-"
			+ "COMISION POR PLANILLA PRIMERA QUINCENA DE DICIEMBRE 2023-"
			+ "PLANILLA SUELDO 1 Q DICIEMBRE DE 2023-"
			+ "BRYAN ADONAY MERINO MARTINEZ-"
			+ "VERONICA LISSETTE CASTRO PONCE-"
			+ "INTELMAX, S.A. DE C.V.-"
			+ "INGRID ELIZABETH MONTES CRUZ-"
			+ "SERVICIOS INDUSTRIALES SANTA CRUZ, S.A. DE C.V.-"
			+ "GRAFICA FENIX S.A. DE C.V.-"
			+ "GIOVANNI FRANCISCO AQUINO-"
			+ "MIGUEL ANTONIO RIVERA LEIVA-"
			+ "WILFREDO ANTONIO CHACON HERNANDEZ-"
			+ "ANA RUTH BARRIENTOS CASTELLON-"
			+ "YOSELYN ABIGAIL MARTINEZ IRAHETA-"
			+ "MANUEL DE JESUS HERNANDEZ-"
			+ "CARLOS JOAQUIN HERNANDEZ RIVAS-"
			+ "COMISION POR PLANILLA SEGUNDA QUINCENA DE DICIEMBRE 2023-"
			+ "PLANILLA SUELDO 2 Q DICIEMBRE DE 2023-"
			+ "ASOCIACION ORDEN CARMELITA DE LA ANTIGUA OBSERVANCIA -"
			+ "HENRY EDGARDO LARREYNAGA MATAMOROS-"
			+ "ALEXANDER ALFREDO RAMIREZ ALVARENGA-"
			+ "MANUEL ALBERTO HERNANDEZ GARCIA-"
			+ "MARIO ERNESTO SERPAS CLAROS"
			+ "";
}
